import Navbar from '@/components/Navbar';

import './globals.css';
import { Space_Grotesk as SpaceGrotesk } from 'next/font/google';

const spaceGrotesk = SpaceGrotesk({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={spaceGrotesk.className}>
        <div className='grid min-h-screen place-content-center bg-blue-950'>
          <div className='sm:w-[500px] md:w-[600px] lg:w-[700px]'>
            <Navbar appTitle='devfinder' />
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
